# Generated by Django 5.2.7 on 2025-11-04 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='location',
            new_name='pickup_location',
        ),
        migrations.RenameField(
            model_name='donationrequest',
            old_name='date_requested',
            new_name='requested_at',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='date_issued',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='date_issued',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='receiverprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='receiverprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(blank=True, choices=[('SPAM', 'Spam'), ('INAPPROPRIATE', 'Inappropriate'), ('SCAM', 'Scam'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_filed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='user_reported',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.donation'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='expiry_date',
            field=models.DateTimeField(blank=True, help_text='e.g., for perishable goods', null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('COLLECTED', 'Collected'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=50),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTJED', 'Rejected'), ('COLLECTED', 'Collected')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='donor_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receiverprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified by admin (FR1)'),
        ),
        migrations.AlterField(
            model_name='receiverprofile',
            name='registration_number',
            field=models.CharField(help_text='Official NGO registration number', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='receiverprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='receiver_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.donation'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DONOR', 'Donor'), ('RECEIVER', 'Receiver'), ('ADMIN', 'Admin')], default='DONOR', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='donationrequest',
            unique_together={('donation', 'receiver')},
        ),
    ]
